language: go

go:
- 1.9.x
- master

install: |
  mkdir -p $HOME/gopath/src/code.cloudfoundry.org/log-cache
  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/code.cloudfoundry.org/log-cache/
  export TRAVIS_BUILD_DIR=$GOPATH/src/code.cloudfoundry.org/log-cache
  go get -t -d -v code.cloudfoundry.org/log-cache/...
script: |
  cd $GOPATH
  cd src/code.cloudfoundry.org/log-cache
  go test ./...
matrix:
  allow_failures:
  - go: master
